#!/bin/sh
#
# Simple script to automatically populate a /dev directory.
# Copyright (c) 2002-2006 Microcross, Inc.  All Rights Reserved
#
# Written by: bgat@billgatliff.com
#
# Usage:
#  makedev [<devpath>] [<createdevnodepath>]
#
# Creates a device node list.
#  <devpath> -- location to build the list,
#               defaults to ${DEFAULT_PREFIX}/dev
#
#  This script uses the host system 'makedev' utility to create
#  device nodes in the target $(ROOTFS)
#
#
#####################################################################

DEFAULT_PREFIX=../out/rootfs


PREFIX=$1
if [ x${PREFIX} = x ]; then
 PREFIX=${DEFAULT_PREFIX}/dev
fi

if [ x${PREFIX} = x/dev ]; then
 echo Cowardly refusing to overwrite my own /dev directory.  Abort.
 exit
fi

CREATE_DEVNODE=$2
if [ x${CREATE_DEVNODE} = x ]; then
 CREATE_DEVNODE=mknod
fi

echo makedevs $Revision: 1.1.1.1 $
echo makedevs: creating device nodes at ${PREFIX} using ${CREATE_DEVNODE}

echo ${PREFIX}
mkdir -p ${PREFIX}

mkdir -p ${PREFIX}/pts
for d in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14; do ${CREATE_DEVNODE} ${PREFIX}/pts/${d} c 136 $d; done

${CREATE_DEVNODE} ${PREFIX}/ptmx c 5 2

${CREATE_DEVNODE} ${PREFIX}/console c 5 1
chmod 644 ${PREFIX}/*console*

for d in 0 1 2; do ${CREATE_DEVNODE} ${PREFIX}/fb${d} c 29 $d; done
ln -sf fb0 ${PREFIX}/fb

${CREATE_DEVNODE} ${PREFIX}/gpio c 10 185

#mkfifo ${PREFIX}/initctl

mkdir -p ${PREFIX}/input
${CREATE_DEVNODE} ${PREFIX}/input/mice c 13 63
${CREATE_DEVNODE} ${PREFIX}/input/event0 c 13 64
${CREATE_DEVNODE} ${PREFIX}/input/ts0 c 13 128


for d in 0 1 2 3 4 5 6 7 8 9; do ${CREATE_DEVNODE} ${PREFIX}/loop${d} b 7 $d; done

for d in 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30; do ${CREATE_DEVNODE} ${PREFIX}/mtd${d} c 90 $d; done
for d in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do ${CREATE_DEVNODE} ${PREFIX}/mtdblock${d} b 31 $d; done

${CREATE_DEVNODE} ${PREFIX}/null c 1 3

for d in 0 1 2 3 4 5 6 7; do ${CREATE_DEVNODE} ${PREFIX}/ram${d} b 31 $d; done

${CREATE_DEVNODE} ${PREFIX}/tty c 5 0

for d in 0 1 2 3; do ${CREATE_DEVNODE} ${PREFIX}/ttyS0${d} c 4 $d; done

${CREATE_DEVNODE} ${PREFIX}/ttyS0 c 4 64
${CREATE_DEVNODE} ${PREFIX}/ttyS1 c 4 65
${CREATE_DEVNODE} ${PREFIX}/ttyS2 c 4 66
${CREATE_DEVNODE} ${PREFIX}/ttyS3 c 4 67

mkdir -p ${PREFIX}/usb && chmod 744 ${PREFIX}/usb

for d in 0 1 2 3 4 5 6 7 8 9; do ${CREATE_DEVNODE} ${PREFIX}/usb/rawUSB${d} c 190 $d; done
for d in 0 1 2 3 4 5 6 7 8 9; do ${CREATE_DEVNODE} ${PREFIX}/usb/ttyUSB${d} c 189 $d; done

${CREATE_DEVNODE} ${PREFIX}/zero c 1 5

${CREATE_DEVNODE} ${PREFIX}/rtc c 10 135

for d in 1 2; do ${CREATE_DEVNODE} ${PREFIX}/sda${d} b 8 $d; done

# OSS device nodes
${CREATE_DEVNODE} ${PREFIX}/mixer c 14 0
${CREATE_DEVNODE} ${PREFIX}/sequencer c 14 1
${CREATE_DEVNODE} ${PREFIX}/dsp c 14 3
${CREATE_DEVNODE} ${PREFIX}/audio c 14 4
${CREATE_DEVNODE} ${PREFIX}/sndstat c 14 6
${CREATE_DEVNODE} ${PREFIX}/music c 14 8
${CREATE_DEVNODE} ${PREFIX}/dmfm c 14 10
${CREATE_DEVNODE} ${PREFIX}/amixer c 14 11
${CREATE_DEVNODE} ${PREFIX}/adsp c 14 12

# ALSA device nodes
mkdir -p ${PREFIX}/snd
${CREATE_DEVNODE} ${PREFIX}/snd/controlC0 c 116 0
${CREATE_DEVNODE} ${PREFIX}/snd/seq c 116 1
${CREATE_DEVNODE} ${PREFIX}/snd/timer c 116 33
${CREATE_DEVNODE} ${PREFIX}/snd/hwC0D0 c 116 4
${CREATE_DEVNODE} ${PREFIX}/snd/hwC0D1 c 116 5
${CREATE_DEVNODE} ${PREFIX}/snd/hwC0D2 c 116 6
${CREATE_DEVNODE} ${PREFIX}/snd/hwC0D3 c 116 8
${CREATE_DEVNODE} ${PREFIX}/snd/pcmC0D0p c 116 16
${CREATE_DEVNODE} ${PREFIX}/snd/pcmC0D1p c 116 17
${CREATE_DEVNODE} ${PREFIX}/snd/pcmC0D0c c 116 24
${CREATE_DEVNODE} ${PREFIX}/snd/pcmC0D1c c 116 25

${CREATE_DEVNODE} ${PREFIX}/random c 1 8
${CREATE_DEVNODE} ${PREFIX}/urandom c 1 9

${CREATE_DEVNODE} ${PREFIX}/ppp c 108 0

# For compact flash
${CREATE_DEVNODE} ${PREFIX}/hda b 3 0
${CREATE_DEVNODE} ${PREFIX}/hda1 b 3 1
${CREATE_DEVNODE} ${PREFIX}/hda2 b 3 2
${CREATE_DEVNODE} ${PREFIX}/hda3 b 3 3
${CREATE_DEVNODE} ${PREFIX}/hda4 b 3 4

# For MMC
${CREATE_DEVNODE} ${PREFIX}/mmcblk0   b 254 0
${CREATE_DEVNODE} ${PREFIX}/mmcblk0p1 b 254 1
${CREATE_DEVNODE} ${PREFIX}/mmcblk0p2 b 254 2
${CREATE_DEVNODE} ${PREFIX}/mmcblk0p3 b 254 3
${CREATE_DEVNODE} ${PREFIX}/mmcblk0p4 b 254 4

# Create /dev/mem
${CREATE_DEVNODE} ${PREFIX}/mem c 1 1
